# Generated by Django 5.1.3 on 2024-12-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_doctorhasespeciality_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorhasEspeciality',
        ),
        migrations.DeleteModel(
            name='Especiality',
        ),
    ]
