# Generated by Django 5.1.3 on 2024-11-26 21:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'El DNI debe tener exactamente 8 dígitos.')])),
                ('phone', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'El número de teléfono debe tener 9 dígitos')])),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1)),
                ('direction', models.CharField(blank=True, max_length=250)),
                ('register_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A positivo'), ('A-', 'A negativo'), ('B+', 'B positivo'), ('B-', 'B negativo'), ('AB+', 'AB positivo'), ('AB-', 'AB negativo'), ('O+', 'O positivo'), ('O-', 'O negativo')], default='O+', max_length=3)),
                ('contact_phone', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'El número de teléfono del contacto de emergencia debe tener 9 dígitos')])),
                ('allergies', models.TextField(blank=True)),
                ('clinical_history', models.TextField(blank=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp', models.CharField(max_length=12, unique=True)),
                ('rne', models.CharField(max_length=12, unique=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
        ),
    ]
