# Generated by Django 5.1.3 on 2024-12-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_doctor_id_remove_pacient_id_person_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
