# Generated by Django 5.1.3 on 2024-12-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_especialty_doctor_specialities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialty',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
