# Generated by Django 5.1.3 on 2024-12-03 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_especialty_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialty',
            new_name='Specialty',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialities',
            new_name='specialties',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cmp',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'The CMP must contain only alphanumeric characters.')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rne',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'The RNE must contain only alphanumeric characters.')]),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'The number of emergency contact phone must have 9 digits')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.CharField(db_index=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'The DNI must contain exactly 8 characters.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'The phone number must have 9 digits')]),
        ),
    ]
